/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as PrivateIndexRouteImport } from './routes/_private/index';
import { Route as PublicPrivacyPolicyIndexRouteImport } from './routes/_public/privacy-policy/index';
import { Route as PublicDevelopIndexRouteImport } from './routes/_public/develop/index';
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index';
import { Route as PublicAppAuthIndexRouteImport } from './routes/_public/app-auth/index';
import { Route as PrivateAddVisitorIndexRouteImport } from './routes/_private/add-visitor/index';
import { Route as PrivateAddDependentIndexRouteImport } from './routes/_private/add-dependent/index';
import { Route as PrivateAccessUserIndexRouteImport } from './routes/_private/access-user/index';
import { Route as PublicNewUserIdRouteImport } from './routes/_public/new-user/$id';
import { Route as PublicAppAuthResetPasswordTokenRouteImport } from './routes/_public/app-auth/reset-password/$token';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicPrivacyPolicyIndexRoute =
  PublicPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => PublicRoute,
  } as any);
const PublicDevelopIndexRoute = PublicDevelopIndexRouteImport.update({
  id: '/develop/',
  path: '/develop/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAppAuthIndexRoute = PublicAppAuthIndexRouteImport.update({
  id: '/app-auth/',
  path: '/app-auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateAddVisitorIndexRoute = PrivateAddVisitorIndexRouteImport.update({
  id: '/add-visitor/',
  path: '/add-visitor/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateAddDependentIndexRoute =
  PrivateAddDependentIndexRouteImport.update({
    id: '/add-dependent/',
    path: '/add-dependent/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateAccessUserIndexRoute = PrivateAccessUserIndexRouteImport.update({
  id: '/access-user/',
  path: '/access-user/',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicNewUserIdRoute = PublicNewUserIdRouteImport.update({
  id: '/new-user/$id',
  path: '/new-user/$id',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAppAuthResetPasswordTokenRoute =
  PublicAppAuthResetPasswordTokenRouteImport.update({
    id: '/app-auth/reset-password/$token',
    path: '/app-auth/reset-password/$token',
    getParentRoute: () => PublicRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute;
  '/new-user/$id': typeof PublicNewUserIdRoute;
  '/access-user/': typeof PrivateAccessUserIndexRoute;
  '/add-dependent/': typeof PrivateAddDependentIndexRoute;
  '/add-visitor/': typeof PrivateAddVisitorIndexRoute;
  '/app-auth/': typeof PublicAppAuthIndexRoute;
  '/contact/': typeof PublicContactIndexRoute;
  '/develop/': typeof PublicDevelopIndexRoute;
  '/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute;
  '/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute;
  '/new-user/$id': typeof PublicNewUserIdRoute;
  '/access-user': typeof PrivateAccessUserIndexRoute;
  '/add-dependent': typeof PrivateAddDependentIndexRoute;
  '/add-visitor': typeof PrivateAddVisitorIndexRoute;
  '/app-auth': typeof PublicAppAuthIndexRoute;
  '/contact': typeof PublicContactIndexRoute;
  '/develop': typeof PublicDevelopIndexRoute;
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute;
  '/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_private/': typeof PrivateIndexRoute;
  '/_public/new-user/$id': typeof PublicNewUserIdRoute;
  '/_private/access-user/': typeof PrivateAccessUserIndexRoute;
  '/_private/add-dependent/': typeof PrivateAddDependentIndexRoute;
  '/_private/add-visitor/': typeof PrivateAddVisitorIndexRoute;
  '/_public/app-auth/': typeof PublicAppAuthIndexRoute;
  '/_public/contact/': typeof PublicContactIndexRoute;
  '/_public/develop/': typeof PublicDevelopIndexRoute;
  '/_public/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute;
  '/_public/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/new-user/$id'
    | '/access-user/'
    | '/add-dependent/'
    | '/add-visitor/'
    | '/app-auth/'
    | '/contact/'
    | '/develop/'
    | '/privacy-policy/'
    | '/app-auth/reset-password/$token';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/new-user/$id'
    | '/access-user'
    | '/add-dependent'
    | '/add-visitor'
    | '/app-auth'
    | '/contact'
    | '/develop'
    | '/privacy-policy'
    | '/app-auth/reset-password/$token';
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/'
    | '/_public/new-user/$id'
    | '/_private/access-user/'
    | '/_private/add-dependent/'
    | '/_private/add-visitor/'
    | '/_public/app-auth/'
    | '/_public/contact/'
    | '/_public/develop/'
    | '/_public/privacy-policy/'
    | '/_public/app-auth/reset-password/$token';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private/': {
      id: '/_private/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/privacy-policy/': {
      id: '/_public/privacy-policy/';
      path: '/privacy-policy';
      fullPath: '/privacy-policy/';
      preLoaderRoute: typeof PublicPrivacyPolicyIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/develop/': {
      id: '/_public/develop/';
      path: '/develop';
      fullPath: '/develop/';
      preLoaderRoute: typeof PublicDevelopIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/contact/': {
      id: '/_public/contact/';
      path: '/contact';
      fullPath: '/contact/';
      preLoaderRoute: typeof PublicContactIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/app-auth/': {
      id: '/_public/app-auth/';
      path: '/app-auth';
      fullPath: '/app-auth/';
      preLoaderRoute: typeof PublicAppAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/add-visitor/': {
      id: '/_private/add-visitor/';
      path: '/add-visitor';
      fullPath: '/add-visitor/';
      preLoaderRoute: typeof PrivateAddVisitorIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/add-dependent/': {
      id: '/_private/add-dependent/';
      path: '/add-dependent';
      fullPath: '/add-dependent/';
      preLoaderRoute: typeof PrivateAddDependentIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/access-user/': {
      id: '/_private/access-user/';
      path: '/access-user';
      fullPath: '/access-user/';
      preLoaderRoute: typeof PrivateAccessUserIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/new-user/$id': {
      id: '/_public/new-user/$id';
      path: '/new-user/$id';
      fullPath: '/new-user/$id';
      preLoaderRoute: typeof PublicNewUserIdRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/app-auth/reset-password/$token': {
      id: '/_public/app-auth/reset-password/$token';
      path: '/app-auth/reset-password/$token';
      fullPath: '/app-auth/reset-password/$token';
      preLoaderRoute: typeof PublicAppAuthResetPasswordTokenRouteImport;
      parentRoute: typeof PublicRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivateAccessUserIndexRoute: typeof PrivateAccessUserIndexRoute;
  PrivateAddDependentIndexRoute: typeof PrivateAddDependentIndexRoute;
  PrivateAddVisitorIndexRoute: typeof PrivateAddVisitorIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAccessUserIndexRoute: PrivateAccessUserIndexRoute,
  PrivateAddDependentIndexRoute: PrivateAddDependentIndexRoute,
  PrivateAddVisitorIndexRoute: PrivateAddVisitorIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicNewUserIdRoute: typeof PublicNewUserIdRoute;
  PublicAppAuthIndexRoute: typeof PublicAppAuthIndexRoute;
  PublicContactIndexRoute: typeof PublicContactIndexRoute;
  PublicDevelopIndexRoute: typeof PublicDevelopIndexRoute;
  PublicPrivacyPolicyIndexRoute: typeof PublicPrivacyPolicyIndexRoute;
  PublicAppAuthResetPasswordTokenRoute: typeof PublicAppAuthResetPasswordTokenRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicNewUserIdRoute: PublicNewUserIdRoute,
  PublicAppAuthIndexRoute: PublicAppAuthIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicDevelopIndexRoute: PublicDevelopIndexRoute,
  PublicPrivacyPolicyIndexRoute: PublicPrivacyPolicyIndexRoute,
  PublicAppAuthResetPasswordTokenRoute: PublicAppAuthResetPasswordTokenRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
